In [97]:
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
WITH FacCount AS (
SELECT memid,facid,COUNT(facid) AS MemFacCount FROM Bookings WHERE memid != 0 GROUP BY memid,facid
),
FacSum AS (
SELECT facid,SUM(MemFacCount) AS MemCountSum FROM FacCount GROUP BY facid
)

SELECT f.name,m.firstname,m.surname, ROUND(fc.MemFacCount * 100.0 / fs.MemCountSum,2) || '%' AS MemUsage
FROM FacCount fc
INNER JOIN Members m 
	ON m.memid = fc.memid
INNER JOIN Facilities f
    ON fc.facid = f.facid
INNER JOIN FacSum fs
    ON fc.facid = fs.facid
ORDER BY f.name
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

def query(conn,query) :
    cur = conn.cursor()
    cur.execute(query)
    for row in cur.fetchall() :
        print(row)

def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    print("2. Query all tasks")
    select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 'Darren', 'Smith', '38.37%')
('Badminton Court', 'Tracy', 'Smith', '9.3%')
('Badminton Court', 'Tim', 'Rownam', '1.16%')
('Badminton Court', 'Gerald', 'Butters', '5.81%')
('Badminton Court', 'Burton', 'Tracy', '0.58%')
('Badminton Court', 'Nancy', 'Dare', '2.91%')
('Badminton Court', 'Tim', 'Boothe', '3.49%')
('Badminton Court', 'Ponder', 'Stibbons', '4.65%')
('Badminton Court', 'Charles', 'Owen', '1.74%')
('Badminton Court', 'David', 'Jones', '2.33%')
('Badminton Court', 'Anne', 'Baker', '2.91%')
('Badminton Court', 'Jemima', 'Farrell', '2.03%')
('Badminton Court', 'Jack', 'Smith', '3.49%')
('Badminton Court', 'Florence', 'Bader', '2.62%')
('Badminton Court', 'Timothy', 'Baker', '2.03%')
('Badminton Court', 'David', 'Pinker', '2.03%')
('Badminton Court', 'Anna', 'Mackenzie', '8.72%')
('Badminton Court', 'Ramnaresh', 'Sarwin', '2.03%')
('Badminton Court', 'Douglas', 'Jones', '0.58%')
('Badminton Court', 'Henry', 'Worthington-Smyth', '1.16%')
('Badminton Court', 'Millicent', 'Purview', '0.58%')
('Badminton Court', 'Hyacinth', 'Tupperware', '0.29%')
('Badminton Court', 'John', 'Hunt', '0.58%')
('Badminton Court', 'Erica', 'Crumpet', '0.58%')
('Massage Room 1', 'Darren', 'Smith', '6.65%')
('Massage Room 1', 'Tracy', 'Smith', '1.43%')
('Massage Room 1', 'Tim', 'Rownam', '19.0%')
('Massage Room 1', 'Janice', 'Joplette', '2.85%')
('Massage Room 1', 'Gerald', 'Butters', '7.6%')
('Massage Room 1', 'Burton', 'Tracy', '7.36%')
('Massage Room 1', 'Nancy', 'Dare', '4.51%')
('Massage Room 1', 'Tim', 'Boothe', '8.55%')
('Massage Room 1', 'Ponder', 'Stibbons', '4.51%')
('Massage Room 1', 'Charles', 'Owen', '2.61%')
('Massage Room 1', 'David', 'Jones', '4.51%')
('Massage Room 1', 'Anne', 'Baker', '0.71%')
('Massage Room 1', 'Jemima', 'Farrell', '6.89%')
('Massage Room 1', 'Jack', 'Smith', '6.41%')
('Massage Room 1', 'Timothy', 'Baker', '5.7%')
('Massage Room 1', 'David', 'Pinker', '0.71%')
('Massage Room 1', 'Matthew', 'Genting', '5.94%')
('Massage Room 1', 'Anna', 'Mackenzie', '0.24%')
('Massage Room 1', 'Joan', 'Coplin', '0.24%')
('Massage Room 1', 'Ramnaresh', 'Sarwin', '1.9%')
('Massage Room 1', 'Henry', 'Worthington-Smyth', '0.24%')
('Massage Room 1', 'Hyacinth', 'Tupperware', '0.24%')
('Massage Room 1', 'John', 'Hunt', '0.71%')
('Massage Room 1', 'Erica', 'Crumpet', '0.48%')
('Massage Room 2', 'Tim', 'Rownam', '7.41%')
('Massage Room 2', 'Janice', 'Joplette', '7.41%')
('Massage Room 2', 'Gerald', 'Butters', '3.7%')
('Massage Room 2', 'Nancy', 'Dare', '18.52%')
('Massage Room 2', 'Charles', 'Owen', '7.41%')
('Massage Room 2', 'David', 'Jones', '14.81%')
('Massage Room 2', 'Anne', 'Baker', '7.41%')
('Massage Room 2', 'Jack', 'Smith', '3.7%')
('Massage Room 2', 'Florence', 'Bader', '7.41%')
('Massage Room 2', 'Matthew', 'Genting', '3.7%')
('Massage Room 2', 'Joan', 'Coplin', '7.41%')
('Massage Room 2', 'Ramnaresh', 'Sarwin', '11.11%')
('Pool Table', 'Darren', 'Smith', '3.58%')
('Pool Table', 'Tracy', 'Smith', '7.79%')
('Pool Table', 'Tim', 'Rownam', '30.78%')
('Pool Table', 'Janice', 'Joplette', '3.45%')
('Pool Table', 'Gerald', 'Butters', '0.77%')
('Pool Table', 'Burton', 'Tracy', '3.83%')
('Pool Table', 'Nancy', 'Dare', '2.43%')
('Pool Table', 'Tim', 'Boothe', '3.19%')
('Pool Table', 'Ponder', 'Stibbons', '1.53%')
('Pool Table', 'Charles', 'Owen', '0.13%')
('Pool Table', 'David', 'Jones', '1.02%')
('Pool Table', 'Anne', 'Baker', '1.53%')
('Pool Table', 'Jemima', 'Farrell', '0.13%')
('Pool Table', 'Jack', 'Smith', '0.89%')
('Pool Table', 'Florence', 'Bader', '2.94%')
('Pool Table', 'Timothy', 'Baker', '10.86%')
('Pool Table', 'David', 'Pinker', '1.15%')
('Pool Table', 'Matthew', 'Genting', '2.3%')
('Pool Table', 'Anna', 'Mackenzie', '8.94%')
('Pool Table', 'Joan', 'Coplin', '1.4%')
('Pool Table', 'Ramnaresh', 'Sarwin', '1.66%')
('Pool Table', 'Douglas', 'Jones', '0.26%')
('Pool Table', 'Henrietta', 'Rumney', '0.38%')
('Pool Table', 'David', 'Farrell', '3.19%')
('Pool Table', 'Henry', 'Worthington-Smyth', '4.21%')
('Pool Table', 'Millicent', 'Purview', '0.64%')
('Pool Table', 'Hyacinth', 'Tupperware', '1.02%')
('Snooker Table', 'Darren', 'Smith', '2.85%')
('Snooker Table', 'Tracy', 'Smith', '10.69%')
('Snooker Table', 'Janice', 'Joplette', '16.15%')
('Snooker Table', 'Gerald', 'Butters', '8.08%')
('Snooker Table', 'Burton', 'Tracy', '4.75%')
('Snooker Table', 'Nancy', 'Dare', '5.46%')
('Snooker Table', 'Tim', 'Boothe', '10.21%')
('Snooker Table', 'Ponder', 'Stibbons', '4.75%')
('Snooker Table', 'Charles', 'Owen', '5.23%')
('Snooker Table', 'David', 'Jones', '0.48%')
('Snooker Table', 'Jemima', 'Farrell', '4.99%')
('Snooker Table', 'Jack', 'Smith', '1.19%')
('Snooker Table', 'Florence', 'Bader', '7.84%')
('Snooker Table', 'David', 'Pinker', '3.8%')
('Snooker Table', 'Matthew', 'Genting', '0.24%')
('Snooker Table', 'Anna', 'Mackenzie', '1.66%')
('Snooker Table', 'Joan', 'Coplin', '2.38%')
('Snooker Table', 'Ramnaresh', 'Sarwin', '4.28%')
('Snooker Table', 'Henrietta', 'Rumney', '3.33%')
('Snooker Table', 'David', 'Farrell', '0.24%')
('Snooker Table', 'Millicent', 'Purview', '0.24%')
('Snooker Table', 'Hyacinth', 'Tupperware', '1.19%')
('Squash Court', 'Darren', 'Smith', '7.18%')
('Squash Court', 'Tracy', 'Smith', '3.08%')
('Squash Court', 'Janice', 'Joplette', '7.18%')
('Squash Court', 'Gerald', 'Butters', '4.62%')
('Squash Court', 'Burton', 'Tracy', '17.95%')
('Squash Court', 'Tim', 'Boothe', '6.15%')
('Squash Court', 'Ponder', 'Stibbons', '1.03%')
('Squash Court', 'Charles', 'Owen', '3.59%')
('Squash Court', 'David', 'Jones', '4.1%')
('Squash Court', 'Anne', 'Baker', '25.13%')
('Squash Court', 'Jemima', 'Farrell', '4.1%')
('Squash Court', 'Jack', 'Smith', '4.62%')
('Squash Court', 'Florence', 'Bader', '1.03%')
('Squash Court', 'Timothy', 'Baker', '2.56%')
('Squash Court', 'David', 'Pinker', '1.54%')
('Squash Court', 'Anna', 'Mackenzie', '1.03%')
('Squash Court', 'Joan', 'Coplin', '0.51%')
('Squash Court', 'Ramnaresh', 'Sarwin', '1.03%')
('Squash Court', 'Douglas', 'Jones', '0.51%')
('Squash Court', 'Henrietta', 'Rumney', '1.03%')
('Squash Court', 'David', 'Farrell', '0.51%')
('Squash Court', 'Millicent', 'Purview', '0.51%')
('Squash Court', 'Hyacinth', 'Tupperware', '0.51%')
('Squash Court', 'John', 'Hunt', '0.51%')
('Table Tennis', 'Darren', 'Smith', '7.27%')
('Table Tennis', 'Tracy', 'Smith', '7.27%')
('Table Tennis', 'Tim', 'Rownam', '17.92%')
('Table Tennis', 'Janice', 'Joplette', '2.34%')
('Table Tennis', 'Gerald', 'Butters', '0.26%')
('Table Tennis', 'Burton', 'Tracy', '6.23%')
('Table Tennis', 'Nancy', 'Dare', '1.3%')
('Table Tennis', 'Tim', 'Boothe', '1.04%')
('Table Tennis', 'Ponder', 'Stibbons', '0.78%')
('Table Tennis', 'Charles', 'Owen', '6.23%')
('Table Tennis', 'David', 'Jones', '2.86%')
('Table Tennis', 'Anne', 'Baker', '0.26%')
('Table Tennis', 'Jemima', 'Farrell', '3.12%')
('Table Tennis', 'Jack', 'Smith', '1.3%')
('Table Tennis', 'Florence', 'Bader', '10.91%')
('Table Tennis', 'Timothy', 'Baker', '6.23%')
('Table Tennis', 'David', 'Pinker', '4.42%')
('Table Tennis', 'Matthew', 'Genting', '6.75%')
('Table Tennis', 'Anna', 'Mackenzie', '4.16%')
('Table Tennis', 'Joan', 'Coplin', '5.45%')
('Table Tennis', 'Ramnaresh', 'Sarwin', '0.78%')
('Table Tennis', 'Henry', 'Worthington-Smyth', '0.78%')
('Table Tennis', 'Millicent', 'Purview', '1.56%')
('Table Tennis', 'John', 'Hunt', '0.26%')
('Table Tennis', 'Erica', 'Crumpet', '0.52%')
('Tennis Court 1', 'Tracy', 'Smith', '9.74%')
('Tennis Court 1', 'Tim', 'Rownam', '1.95%')
('Tennis Court 1', 'Janice', 'Joplette', '6.17%')
('Tennis Court 1', 'Gerald', 'Butters', '18.51%')
('Tennis Court 1', 'Burton', 'Tracy', '10.06%')
('Tennis Court 1', 'Nancy', 'Dare', '8.12%')
('Tennis Court 1', 'Tim', 'Boothe', '1.3%')
('Tennis Court 1', 'Ponder', 'Stibbons', '0.32%')
('Tennis Court 1', 'Charles', 'Owen', '5.52%')
('Tennis Court 1', 'David', 'Jones', '8.12%')
('Tennis Court 1', 'Anne', 'Baker', '1.95%')
('Tennis Court 1', 'Jemima', 'Farrell', '0.32%')
('Tennis Court 1', 'Jack', 'Smith', '7.14%')
('Tennis Court 1', 'Florence', 'Bader', '0.32%')
('Tennis Court 1', 'Timothy', 'Baker', '4.55%')
('Tennis Court 1', 'David', 'Pinker', '5.19%')
('Tennis Court 1', 'Matthew', 'Genting', '0.32%')
('Tennis Court 1', 'Joan', 'Coplin', '2.27%')
('Tennis Court 1', 'Ramnaresh', 'Sarwin', '1.62%')
('Tennis Court 1', 'Douglas', 'Jones', '2.92%')
('Tennis Court 1', 'David', 'Farrell', '1.95%')
('Tennis Court 1', 'John', 'Hunt', '1.3%')
('Tennis Court 1', 'Erica', 'Crumpet', '0.32%')
('Tennis Court 2', 'Darren', 'Smith', '6.88%')
('Tennis Court 2', 'Tracy', 'Smith', '0.72%')
('Tennis Court 2', 'Tim', 'Rownam', '2.17%')
('Tennis Court 2', 'Janice', 'Joplette', '2.9%')
('Tennis Court 2', 'Gerald', 'Butters', '1.09%')
('Tennis Court 2', 'Burton', 'Tracy', '1.09%')
('Tennis Court 2', 'Nancy', 'Dare', '3.99%')
('Tennis Court 2', 'Tim', 'Boothe', '18.84%')
('Tennis Court 2', 'Ponder', 'Stibbons', '11.23%')
('Tennis Court 2', 'Charles', 'Owen', '14.86%')
('Tennis Court 2', 'David', 'Jones', '10.87%')
('Tennis Court 2', 'Anne', 'Baker', '12.68%')
('Tennis Court 2', 'Jemima', 'Farrell', '0.36%')
('Tennis Court 2', 'Jack', 'Smith', '0.36%')
('Tennis Court 2', 'Florence', 'Bader', '2.9%')
('Tennis Court 2', 'Timothy', 'Baker', '2.54%')
('Tennis Court 2', 'Ramnaresh', 'Sarwin', '3.99%')
('Tennis Court 2', 'Henrietta', 'Rumney', '0.36%')
('Tennis Court 2', 'David', 'Farrell', '0.36%')
('Tennis Court 2', 'Millicent', 'Purview', '0.36%')
('Tennis Court 2', 'John', 'Hunt', '1.45%')